/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_model_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[36] = 
  {10, 3, 0, 10, 20, 30, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9};
static const casadi_int casadi_s1[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s2[6] = {0, 2, 5, 6, 7, 8};
static const casadi_int casadi_s3[3] = {5, 1, 1};
static const casadi_int casadi_s4[3] = {3, 1, 1};
static const casadi_int casadi_s5[3] = {0, 1, 1};
static const casadi_int casadi_s6[3] = {0, 0, 1};
static const casadi_int casadi_s7[3] = {9, 1, 1};
static const casadi_int casadi_s8[24] = 
  {8, 9, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 12, 3, 4, 5, 6,
  7, 0, 1, 2, 3, 4, 6, 7};
static const casadi_int casadi_s9[3] = {9, 0, 1};

/* External functions */
int jac_y_expr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int y_expr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* y_expr:(i0[3])->(o0[1x10]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (y_expr(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_y_expr:(i0[3],out_o0[1x10,0nz])->(jac_o0_i0[10x3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_y_expr(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* robot_model_cost_y_0_fun_jac_ut_xt:(i0[5],i1[3],i2[0],i3[],i4[0])->(o0[9],o1[8x9,12nz],o2[9x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+3, *rr, w00, w01, w02, w03, w04, w05, w06, w07, *w08=w+18, *w09=w+21;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21;
  casadi_real w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+54;
  casadi_real *w34=w+66, *w36=w+71, *w38=w+101, *w39=w+131, *w40=w+141, w41, w42, w43, w44, w45, w46, w47;
  casadi_real *w48=w+158, *w49=w+164, *w50=w+170, *w51=w+172;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #4: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #6: @2 = input[0][3] */
  w02 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #8: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @3 */
  if (res[0]) res[0][4] = w03;
  /* #10: @4 = input[1][0] */
  w04 = arg[1] ? arg[1][0] : 0;
  /* #11: output[0][5] = @4 */
  if (res[0]) res[0][5] = w04;
  /* #12: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #13: output[0][6] = @4 */
  if (res[0]) res[0][6] = w04;
  /* #14: @4 = input[1][2] */
  w04 = arg[1] ? arg[1][2] : 0;
  /* #15: output[0][7] = @4 */
  if (res[0]) res[0][7] = w04;
  /* #16: @4 = 4.5 */
  w04 = 4.5000000000000000e+00;
  /* #17: @5 = 0 */
  w05 = 0.;
  /* #18: @3 = fmax(@3,@5) */
  w03  = casadi_fmax(w03,w05);
  /* #19: @6 = 5 */
  w06 = 5.;
  /* #20: @3 = fmin(@3,@6) */
  w03  = casadi_fmin(w03,w06);
  /* #21: @7 = (@4<=@3) */
  w07  = (w04<=w03);
  /* #22: @6 = (@3<@6) */
  w06  = (w03<w06);
  /* #23: @7 = (@7&&@6) */
  w07  = (w07&&w06);
  /* #24: @8 = vertcat(@0, @1, @2) */
  rr=w08;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  /* #25: @9 = y_expr(@8) */
  arg1[0]=w08;
  res1[0]=w09;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #26: @0 = @9[9] */
  for (rr=(&w00), cs=w09+9; cs!=w09+10; cs+=1) *rr++ = *cs;
  /* #27: @1 = (@7?@0:0) */
  w01  = (w07?w00:0);
  /* #28: @2 = (!@7) */
  w02 = (! w07 );
  /* #29: @6 = 4 */
  w06 = 4.;
  /* #30: @10 = (@6<=@3) */
  w10  = (w06<=w03);
  /* #31: @4 = (@3<@4) */
  w04  = (w03<w04);
  /* #32: @10 = (@10&&@4) */
  w10  = (w10&&w04);
  /* #33: @4 = @9[8] */
  for (rr=(&w04), cs=w09+8; cs!=w09+9; cs+=1) *rr++ = *cs;
  /* #34: @4 = (@10?@4:0) */
  w04  = (w10?w04:0);
  /* #35: @11 = (!@10) */
  w11 = (! w10 );
  /* #36: @12 = 3.5 */
  w12 = 3.5000000000000000e+00;
  /* #37: @13 = (@12<=@3) */
  w13  = (w12<=w03);
  /* #38: @6 = (@3<@6) */
  w06  = (w03<w06);
  /* #39: @13 = (@13&&@6) */
  w13  = (w13&&w06);
  /* #40: @6 = @9[7] */
  for (rr=(&w06), cs=w09+7; cs!=w09+8; cs+=1) *rr++ = *cs;
  /* #41: @6 = (@13?@6:0) */
  w06  = (w13?w06:0);
  /* #42: @14 = (!@13) */
  w14 = (! w13 );
  /* #43: @15 = 3 */
  w15 = 3.;
  /* #44: @16 = (@15<=@3) */
  w16  = (w15<=w03);
  /* #45: @12 = (@3<@12) */
  w12  = (w03<w12);
  /* #46: @16 = (@16&&@12) */
  w16  = (w16&&w12);
  /* #47: @12 = @9[6] */
  for (rr=(&w12), cs=w09+6; cs!=w09+7; cs+=1) *rr++ = *cs;
  /* #48: @12 = (@16?@12:0) */
  w12  = (w16?w12:0);
  /* #49: @17 = (!@16) */
  w17 = (! w16 );
  /* #50: @18 = 2.5 */
  w18 = 2.5000000000000000e+00;
  /* #51: @19 = (@18<=@3) */
  w19  = (w18<=w03);
  /* #52: @15 = (@3<@15) */
  w15  = (w03<w15);
  /* #53: @19 = (@19&&@15) */
  w19  = (w19&&w15);
  /* #54: @15 = @9[5] */
  for (rr=(&w15), cs=w09+5; cs!=w09+6; cs+=1) *rr++ = *cs;
  /* #55: @15 = (@19?@15:0) */
  w15  = (w19?w15:0);
  /* #56: @20 = (!@19) */
  w20 = (! w19 );
  /* #57: @21 = 2 */
  w21 = 2.;
  /* #58: @22 = (@21<=@3) */
  w22  = (w21<=w03);
  /* #59: @18 = (@3<@18) */
  w18  = (w03<w18);
  /* #60: @22 = (@22&&@18) */
  w22  = (w22&&w18);
  /* #61: @18 = @9[4] */
  for (rr=(&w18), cs=w09+4; cs!=w09+5; cs+=1) *rr++ = *cs;
  /* #62: @18 = (@22?@18:0) */
  w18  = (w22?w18:0);
  /* #63: @23 = (!@22) */
  w23 = (! w22 );
  /* #64: @24 = 1.5 */
  w24 = 1.5000000000000000e+00;
  /* #65: @25 = (@24<=@3) */
  w25  = (w24<=w03);
  /* #66: @21 = (@3<@21) */
  w21  = (w03<w21);
  /* #67: @25 = (@25&&@21) */
  w25  = (w25&&w21);
  /* #68: @21 = @9[3] */
  for (rr=(&w21), cs=w09+3; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #69: @21 = (@25?@21:0) */
  w21  = (w25?w21:0);
  /* #70: @26 = (!@25) */
  w26 = (! w25 );
  /* #71: @27 = 1 */
  w27 = 1.;
  /* #72: @28 = (@27<=@3) */
  w28  = (w27<=w03);
  /* #73: @24 = (@3<@24) */
  w24  = (w03<w24);
  /* #74: @28 = (@28&&@24) */
  w28  = (w28&&w24);
  /* #75: @24 = @9[2] */
  for (rr=(&w24), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #76: @24 = (@28?@24:0) */
  w24  = (w28?w24:0);
  /* #77: @29 = (!@28) */
  w29 = (! w28 );
  /* #78: @30 = 0.5 */
  w30 = 5.0000000000000000e-01;
  /* #79: @31 = (@30<=@3) */
  w31  = (w30<=w03);
  /* #80: @27 = (@3<@27) */
  w27  = (w03<w27);
  /* #81: @31 = (@31&&@27) */
  w31  = (w31&&w27);
  /* #82: @27 = @9[1] */
  for (rr=(&w27), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #83: @27 = (@31?@27:0) */
  w27  = (w31?w27:0);
  /* #84: @32 = (!@31) */
  w32 = (! w31 );
  /* #85: @5 = (@5<=@3) */
  w05  = (w05<=w03);
  /* #86: @3 = (@3<@30) */
  w03  = (w03<w30);
  /* #87: @5 = (@5&&@3) */
  w05  = (w05&&w03);
  /* #88: @3 = @9[0] */
  for (rr=(&w03), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #89: @3 = (@5?@3:0) */
  w03  = (w05?w03:0);
  /* #90: @30 = (!@5) */
  w30 = (! w05 );
  /* #91: @0 = (@30?@0:0) */
  w00  = (w30?w00:0);
  /* #92: @3 = (@3+@0) */
  w03 += w00;
  /* #93: @3 = (@32?@3:0) */
  w03  = (w32?w03:0);
  /* #94: @27 = (@27+@3) */
  w27 += w03;
  /* #95: @27 = (@29?@27:0) */
  w27  = (w29?w27:0);
  /* #96: @24 = (@24+@27) */
  w24 += w27;
  /* #97: @24 = (@26?@24:0) */
  w24  = (w26?w24:0);
  /* #98: @21 = (@21+@24) */
  w21 += w24;
  /* #99: @21 = (@23?@21:0) */
  w21  = (w23?w21:0);
  /* #100: @18 = (@18+@21) */
  w18 += w21;
  /* #101: @18 = (@20?@18:0) */
  w18  = (w20?w18:0);
  /* #102: @15 = (@15+@18) */
  w15 += w18;
  /* #103: @15 = (@17?@15:0) */
  w15  = (w17?w15:0);
  /* #104: @12 = (@12+@15) */
  w12 += w15;
  /* #105: @12 = (@14?@12:0) */
  w12  = (w14?w12:0);
  /* #106: @6 = (@6+@12) */
  w06 += w12;
  /* #107: @6 = (@11?@6:0) */
  w06  = (w11?w06:0);
  /* #108: @4 = (@4+@6) */
  w04 += w06;
  /* #109: @4 = (@2?@4:0) */
  w04  = (w02?w04:0);
  /* #110: @1 = (@1+@4) */
  w01 += w04;
  /* #111: output[0][8] = @1 */
  if (res[0]) res[0][8] = w01;
  /* #112: @33 = zeros(8x9,12nz) */
  casadi_clear(w33, 12);
  /* #113: @34 = ones(8x1,5nz) */
  casadi_fill(w34, 5, 1.);
  /* #114: {@1, @4, @6, @12, NULL, @15, NULL, NULL} = vertsplit(@34) */
  w01 = w34[0];
  w04 = w34[1];
  w06 = w34[2];
  w12 = w34[3];
  w15 = w34[4];
  /* #115: @35 = 00 */
  /* #116: @36 = zeros(10x3) */
  casadi_clear(w36, 30);
  /* #117: @37 = zeros(1x10,0nz) */
  /* #118: @38 = jac_y_expr(@8, @37) */
  arg1[0]=w08;
  arg1[1]=0;
  res1[0]=w38;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #119: @18 = vertcat(@12, @35, @35) */
  rr=(&w18);
  *rr++ = w12;
  /* #120: @21 = ones(8x1,1nz) */
  w21 = 1.;
  /* #121: {NULL, NULL, NULL, NULL, @24, NULL, NULL, NULL} = vertsplit(@21) */
  w24 = w21;
  /* #122: @21 = vertcat(@35, @24, @35) */
  rr=(&w21);
  *rr++ = w24;
  /* #123: @27 = ones(8x1,1nz) */
  w27 = 1.;
  /* #124: {NULL, NULL, NULL, NULL, NULL, NULL, @3, NULL} = vertsplit(@27) */
  w03 = w27;
  /* #125: @27 = vertcat(@35, @35, @3) */
  rr=(&w27);
  *rr++ = w03;
  /* #126: @8 = horzcat(@18, @21, @27) */
  rr=w08;
  *rr++ = w18;
  *rr++ = w21;
  *rr++ = w27;
  /* #127: @36 = mac(@38,@8,@36) */
  casadi_mtimes(w38, casadi_s0, w08, casadi_s1, w36, casadi_s0, w, 0);
  /* #128: {@9, @39, @40} = horzsplit(@36) */
  casadi_copy(w36, 10, w09);
  casadi_copy(w36+10, 10, w39);
  casadi_copy(w36+20, 10, w40);
  /* #129: @9 = @9' */
  /* #130: @18 = @9[9] */
  for (rr=(&w18), cs=w09+9; cs!=w09+10; cs+=1) *rr++ = *cs;
  /* #131: @21 = (@7?@18:0) */
  w21  = (w07?w18:0);
  /* #132: @27 = @9[8] */
  for (rr=(&w27), cs=w09+8; cs!=w09+9; cs+=1) *rr++ = *cs;
  /* #133: @27 = (@10?@27:0) */
  w27  = (w10?w27:0);
  /* #134: @0 = @9[7] */
  for (rr=(&w00), cs=w09+7; cs!=w09+8; cs+=1) *rr++ = *cs;
  /* #135: @0 = (@13?@0:0) */
  w00  = (w13?w00:0);
  /* #136: @41 = @9[6] */
  for (rr=(&w41), cs=w09+6; cs!=w09+7; cs+=1) *rr++ = *cs;
  /* #137: @41 = (@16?@41:0) */
  w41  = (w16?w41:0);
  /* #138: @42 = @9[5] */
  for (rr=(&w42), cs=w09+5; cs!=w09+6; cs+=1) *rr++ = *cs;
  /* #139: @42 = (@19?@42:0) */
  w42  = (w19?w42:0);
  /* #140: @43 = @9[4] */
  for (rr=(&w43), cs=w09+4; cs!=w09+5; cs+=1) *rr++ = *cs;
  /* #141: @43 = (@22?@43:0) */
  w43  = (w22?w43:0);
  /* #142: @44 = @9[3] */
  for (rr=(&w44), cs=w09+3; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #143: @44 = (@25?@44:0) */
  w44  = (w25?w44:0);
  /* #144: @45 = @9[2] */
  for (rr=(&w45), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #145: @45 = (@28?@45:0) */
  w45  = (w28?w45:0);
  /* #146: @46 = @9[1] */
  for (rr=(&w46), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #147: @46 = (@31?@46:0) */
  w46  = (w31?w46:0);
  /* #148: @47 = @9[0] */
  for (rr=(&w47), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #149: @47 = (@5?@47:0) */
  w47  = (w05?w47:0);
  /* #150: @18 = (@30?@18:0) */
  w18  = (w30?w18:0);
  /* #151: @47 = (@47+@18) */
  w47 += w18;
  /* #152: @47 = (@32?@47:0) */
  w47  = (w32?w47:0);
  /* #153: @46 = (@46+@47) */
  w46 += w47;
  /* #154: @46 = (@29?@46:0) */
  w46  = (w29?w46:0);
  /* #155: @45 = (@45+@46) */
  w45 += w46;
  /* #156: @45 = (@26?@45:0) */
  w45  = (w26?w45:0);
  /* #157: @44 = (@44+@45) */
  w44 += w45;
  /* #158: @44 = (@23?@44:0) */
  w44  = (w23?w44:0);
  /* #159: @43 = (@43+@44) */
  w43 += w44;
  /* #160: @43 = (@20?@43:0) */
  w43  = (w20?w43:0);
  /* #161: @42 = (@42+@43) */
  w42 += w43;
  /* #162: @42 = (@17?@42:0) */
  w42  = (w17?w42:0);
  /* #163: @41 = (@41+@42) */
  w41 += w42;
  /* #164: @41 = (@14?@41:0) */
  w41  = (w14?w41:0);
  /* #165: @0 = (@0+@41) */
  w00 += w41;
  /* #166: @0 = (@11?@0:0) */
  w00  = (w11?w00:0);
  /* #167: @27 = (@27+@0) */
  w27 += w00;
  /* #168: @27 = (@2?@27:0) */
  w27  = (w02?w27:0);
  /* #169: @21 = (@21+@27) */
  w21 += w27;
  /* #170: @48 = vertcat(@12, @35, @15, @35, @35, @1, @4, @6, @21) */
  rr=w48;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w01;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w21;
  /* #171: @49 = @48[:6] */
  for (rr=w49, cs=w48+0; cs!=w48+6; cs+=1) *rr++ = *cs;
  /* #172: (@33[0, 2, 5, 6, 7, 8] = @49) */
  for (cii=casadi_s2, rr=w33, cs=w49; cii!=casadi_s2+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #173: @39 = @39' */
  /* #174: @12 = @39[9] */
  for (rr=(&w12), cs=w39+9; cs!=w39+10; cs+=1) *rr++ = *cs;
  /* #175: @15 = (@7?@12:0) */
  w15  = (w07?w12:0);
  /* #176: @1 = @39[8] */
  for (rr=(&w01), cs=w39+8; cs!=w39+9; cs+=1) *rr++ = *cs;
  /* #177: @1 = (@10?@1:0) */
  w01  = (w10?w01:0);
  /* #178: @4 = @39[7] */
  for (rr=(&w04), cs=w39+7; cs!=w39+8; cs+=1) *rr++ = *cs;
  /* #179: @4 = (@13?@4:0) */
  w04  = (w13?w04:0);
  /* #180: @6 = @39[6] */
  for (rr=(&w06), cs=w39+6; cs!=w39+7; cs+=1) *rr++ = *cs;
  /* #181: @6 = (@16?@6:0) */
  w06  = (w16?w06:0);
  /* #182: @21 = @39[5] */
  for (rr=(&w21), cs=w39+5; cs!=w39+6; cs+=1) *rr++ = *cs;
  /* #183: @21 = (@19?@21:0) */
  w21  = (w19?w21:0);
  /* #184: @27 = @39[4] */
  for (rr=(&w27), cs=w39+4; cs!=w39+5; cs+=1) *rr++ = *cs;
  /* #185: @27 = (@22?@27:0) */
  w27  = (w22?w27:0);
  /* #186: @0 = @39[3] */
  for (rr=(&w00), cs=w39+3; cs!=w39+4; cs+=1) *rr++ = *cs;
  /* #187: @0 = (@25?@0:0) */
  w00  = (w25?w00:0);
  /* #188: @41 = @39[2] */
  for (rr=(&w41), cs=w39+2; cs!=w39+3; cs+=1) *rr++ = *cs;
  /* #189: @41 = (@28?@41:0) */
  w41  = (w28?w41:0);
  /* #190: @42 = @39[1] */
  for (rr=(&w42), cs=w39+1; cs!=w39+2; cs+=1) *rr++ = *cs;
  /* #191: @42 = (@31?@42:0) */
  w42  = (w31?w42:0);
  /* #192: @43 = @39[0] */
  for (rr=(&w43), cs=w39+0; cs!=w39+1; cs+=1) *rr++ = *cs;
  /* #193: @43 = (@5?@43:0) */
  w43  = (w05?w43:0);
  /* #194: @12 = (@30?@12:0) */
  w12  = (w30?w12:0);
  /* #195: @43 = (@43+@12) */
  w43 += w12;
  /* #196: @43 = (@32?@43:0) */
  w43  = (w32?w43:0);
  /* #197: @42 = (@42+@43) */
  w42 += w43;
  /* #198: @42 = (@29?@42:0) */
  w42  = (w29?w42:0);
  /* #199: @41 = (@41+@42) */
  w41 += w42;
  /* #200: @41 = (@26?@41:0) */
  w41  = (w26?w41:0);
  /* #201: @0 = (@0+@41) */
  w00 += w41;
  /* #202: @0 = (@23?@0:0) */
  w00  = (w23?w00:0);
  /* #203: @27 = (@27+@0) */
  w27 += w00;
  /* #204: @27 = (@20?@27:0) */
  w27  = (w20?w27:0);
  /* #205: @21 = (@21+@27) */
  w21 += w27;
  /* #206: @21 = (@17?@21:0) */
  w21  = (w17?w21:0);
  /* #207: @6 = (@6+@21) */
  w06 += w21;
  /* #208: @6 = (@14?@6:0) */
  w06  = (w14?w06:0);
  /* #209: @4 = (@4+@6) */
  w04 += w06;
  /* #210: @4 = (@11?@4:0) */
  w04  = (w11?w04:0);
  /* #211: @1 = (@1+@4) */
  w01 += w04;
  /* #212: @1 = (@2?@1:0) */
  w01  = (w02?w01:0);
  /* #213: @15 = (@15+@1) */
  w15 += w01;
  /* #214: @50 = vertcat(@35, @24, @35, @35, @35, @35, @35, @35, @15) */
  rr=w50;
  *rr++ = w24;
  *rr++ = w15;
  /* #215: @51 = @50[:2] */
  for (rr=w51, cs=w50+0; cs!=w50+2; cs+=1) *rr++ = *cs;
  /* #216: (@33[1:17:8] = @51) */
  for (rr=w33+1, cs=w51; rr!=w33+17; rr+=8) *rr = *cs++;
  /* #217: @40 = @40' */
  /* #218: @24 = @40[9] */
  for (rr=(&w24), cs=w40+9; cs!=w40+10; cs+=1) *rr++ = *cs;
  /* #219: @7 = (@7?@24:0) */
  w07  = (w07?w24:0);
  /* #220: @15 = @40[8] */
  for (rr=(&w15), cs=w40+8; cs!=w40+9; cs+=1) *rr++ = *cs;
  /* #221: @10 = (@10?@15:0) */
  w10  = (w10?w15:0);
  /* #222: @15 = @40[7] */
  for (rr=(&w15), cs=w40+7; cs!=w40+8; cs+=1) *rr++ = *cs;
  /* #223: @13 = (@13?@15:0) */
  w13  = (w13?w15:0);
  /* #224: @15 = @40[6] */
  for (rr=(&w15), cs=w40+6; cs!=w40+7; cs+=1) *rr++ = *cs;
  /* #225: @16 = (@16?@15:0) */
  w16  = (w16?w15:0);
  /* #226: @15 = @40[5] */
  for (rr=(&w15), cs=w40+5; cs!=w40+6; cs+=1) *rr++ = *cs;
  /* #227: @19 = (@19?@15:0) */
  w19  = (w19?w15:0);
  /* #228: @15 = @40[4] */
  for (rr=(&w15), cs=w40+4; cs!=w40+5; cs+=1) *rr++ = *cs;
  /* #229: @22 = (@22?@15:0) */
  w22  = (w22?w15:0);
  /* #230: @15 = @40[3] */
  for (rr=(&w15), cs=w40+3; cs!=w40+4; cs+=1) *rr++ = *cs;
  /* #231: @25 = (@25?@15:0) */
  w25  = (w25?w15:0);
  /* #232: @15 = @40[2] */
  for (rr=(&w15), cs=w40+2; cs!=w40+3; cs+=1) *rr++ = *cs;
  /* #233: @28 = (@28?@15:0) */
  w28  = (w28?w15:0);
  /* #234: @15 = @40[1] */
  for (rr=(&w15), cs=w40+1; cs!=w40+2; cs+=1) *rr++ = *cs;
  /* #235: @31 = (@31?@15:0) */
  w31  = (w31?w15:0);
  /* #236: @15 = @40[0] */
  for (rr=(&w15), cs=w40+0; cs!=w40+1; cs+=1) *rr++ = *cs;
  /* #237: @5 = (@5?@15:0) */
  w05  = (w05?w15:0);
  /* #238: @30 = (@30?@24:0) */
  w30  = (w30?w24:0);
  /* #239: @5 = (@5+@30) */
  w05 += w30;
  /* #240: @32 = (@32?@5:0) */
  w32  = (w32?w05:0);
  /* #241: @31 = (@31+@32) */
  w31 += w32;
  /* #242: @29 = (@29?@31:0) */
  w29  = (w29?w31:0);
  /* #243: @28 = (@28+@29) */
  w28 += w29;
  /* #244: @26 = (@26?@28:0) */
  w26  = (w26?w28:0);
  /* #245: @25 = (@25+@26) */
  w25 += w26;
  /* #246: @23 = (@23?@25:0) */
  w23  = (w23?w25:0);
  /* #247: @22 = (@22+@23) */
  w22 += w23;
  /* #248: @20 = (@20?@22:0) */
  w20  = (w20?w22:0);
  /* #249: @19 = (@19+@20) */
  w19 += w20;
  /* #250: @17 = (@17?@19:0) */
  w17  = (w17?w19:0);
  /* #251: @16 = (@16+@17) */
  w16 += w17;
  /* #252: @14 = (@14?@16:0) */
  w14  = (w14?w16:0);
  /* #253: @13 = (@13+@14) */
  w13 += w14;
  /* #254: @11 = (@11?@13:0) */
  w11  = (w11?w13:0);
  /* #255: @10 = (@10+@11) */
  w10 += w11;
  /* #256: @2 = (@2?@10:0) */
  w02  = (w02?w10:0);
  /* #257: @7 = (@7+@2) */
  w07 += w02;
  /* #258: @51 = vertcat(@35, @35, @35, @3, @35, @35, @35, @35, @7) */
  rr=w51;
  *rr++ = w03;
  *rr++ = w07;
  /* #259: @50 = @51[:2] */
  for (rr=w50, cs=w51+0; cs!=w51+2; cs+=1) *rr++ = *cs;
  /* #260: (@33[3:17:7] = @50) */
  for (rr=w33+3, cs=w50; rr!=w33+17; rr+=7) *rr = *cs++;
  /* #261: @3 = ones(8x1,1nz) */
  w03 = 1.;
  /* #262: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7} = vertsplit(@3) */
  w07 = w03;
  /* #263: (@33[4] = @7) */
  for (rr=w33+4, cs=(&w07); rr!=w33+5; rr+=1) *rr = *cs++;
  /* #264: output[1][0] = @33 */
  casadi_copy(w33, 12, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real robot_model_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 174;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 11*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 174*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
