/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[5] = {0, 1, 3, 5, 6};
static const casadi_int casadi_s1[13] = 
  {5, 3, 0, 1, 2, 7, 2, 3,
  0, 1, 2, 3, 4};
static const casadi_int casadi_s2[15] = 
  {3, 5, 0, 1, 2, 4, 6, 7,
  2, 2, 0, 2, 1, 2, 2};
static const casadi_int casadi_s3[17] = 
  {5, 3, 0, 3, 6, 11, 0, 1,
  2, 0, 1, 3, 0, 1, 2, 3,
  4};
static const casadi_int casadi_s4[12] = 
  {5, 3, 0, 2, 4, 6, 0, 1,
  0, 1, 0, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[3] = {5, 5, 1};
static const casadi_int casadi_s7[3] = {5, 3, 1};
static const casadi_int casadi_s8[3] = {3, 1, 1};
static const casadi_int casadi_s9[3] = {0, 1, 1};
static const casadi_int casadi_s10[18] = 
  {5, 5, 0, 2, 4, 6, 8, 10,
  0, 1, 0, 1, 0, 1, 0, 1,
  0, 1};

static const casadi_real casadi_zeros[25] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* robot_model_expl_vde_forw:(i0[5],i1[5x5],i2[5x3],i3[3],i4[0])->(o0[5],o1[5x5,10nz],o2[5x3,11nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, *w09=w+14, *w10=w+19;
  casadi_real *w17=w+69, *w18=w+71, *w19=w+78, *w20=w+80, *w21=w+87, *w23=w+113, *w24=w+115, *w25=w+121;
  const casadi_int *cii;
  const casadi_real *cs, *wr09, *wr10, *wr11, *wr12, *wr13, *wr14, *wr15, *wr22;
  /* #0: @0 = input[3][2] */
  w00 = arg[3] ? arg[3][2] : 0;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = input[0][3] */
  w02 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = (@1*@3) */
  w04  = (w01*w03);
  /* #5: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #6: @5 = (@1*@2) */
  w05  = (w01*w02);
  /* #7: @6 = input[3][0] */
  w06 = arg[3] ? arg[3][0] : 0;
  /* #8: @7 = input[3][1] */
  w07 = arg[3] ? arg[3][1] : 0;
  /* #9: @8 = 1 */
  w08 = 1.;
  /* #10: @9 = vertcat(@4, @5, @6, @7, @8) */
  rr=w09;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #11: @10 = (@0*@9) */
  for (i=0, rr=w10, cs=w09; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #12: output[0][0] = @10 */
  casadi_copy(w10, 5, res[0]);
  /* #13: @11 = input[1][0] */
  wr11 = arg[1] ? arg[1] : casadi_zeros;
  /* #14: {@10, @12, @13, @14, @15} = horzsplit(@11) */
  wr10 = wr11;
  wr12 = wr11+5;
  wr13 = wr11+10;
  wr14 = wr11+15;
  wr15 = wr11+20;
  /* #15: {NULL, NULL, @4, @5, NULL} = vertsplit(@10) */
  w04 = wr10[2];
  w05 = wr10[3];
  /* #16: @6 = (@3*@4) */
  w06  = (w03*w04);
  /* #17: @7 = (@2*@5) */
  w07  = (w02*w05);
  /* #18: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #19: @6 = (@6-@7) */
  w06 -= w07;
  /* #20: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #21: @5 = (@3*@5) */
  w05  = (w03*w05);
  /* #22: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #23: @4 = (@4+@5) */
  w04 += w05;
  /* #24: @16 = 00 */
  /* #25: @17 = vertcat(@6, @4, @16, @16, @16) */
  rr=w17;
  *rr++ = w06;
  *rr++ = w04;
  /* #26: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #27: output[1][0] = @17 */
  casadi_copy(w17, 2, res[1]);
  /* #28: {NULL, NULL, @6, @4, NULL} = vertsplit(@12) */
  w06 = wr12[2];
  w04 = wr12[3];
  /* #29: @5 = (@3*@6) */
  w05  = (w03*w06);
  /* #30: @7 = (@2*@4) */
  w07  = (w02*w04);
  /* #31: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #32: @5 = (@5-@7) */
  w05 -= w07;
  /* #33: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #34: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #35: @4 = (@1*@4) */
  w04  = (w01*w04);
  /* #36: @6 = (@6+@4) */
  w06 += w04;
  /* #37: @17 = vertcat(@5, @6, @16, @16, @16) */
  rr=w17;
  *rr++ = w05;
  *rr++ = w06;
  /* #38: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #39: output[1][1] = @17 */
  if (res[1]) casadi_copy(w17, 2, res[1]+2);
  /* #40: {NULL, NULL, @5, @6, NULL} = vertsplit(@13) */
  w05 = wr13[2];
  w06 = wr13[3];
  /* #41: @4 = (@3*@5) */
  w04  = (w03*w05);
  /* #42: @7 = (@2*@6) */
  w07  = (w02*w06);
  /* #43: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #44: @4 = (@4-@7) */
  w04 -= w07;
  /* #45: @5 = (@2*@5) */
  w05  = (w02*w05);
  /* #46: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #47: @6 = (@1*@6) */
  w06  = (w01*w06);
  /* #48: @5 = (@5+@6) */
  w05 += w06;
  /* #49: @17 = vertcat(@4, @5, @16, @16, @16) */
  rr=w17;
  *rr++ = w04;
  *rr++ = w05;
  /* #50: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #51: output[1][2] = @17 */
  if (res[1]) casadi_copy(w17, 2, res[1]+4);
  /* #52: {NULL, NULL, @4, @5, NULL} = vertsplit(@14) */
  w04 = wr14[2];
  w05 = wr14[3];
  /* #53: @6 = (@3*@4) */
  w06  = (w03*w04);
  /* #54: @7 = (@2*@5) */
  w07  = (w02*w05);
  /* #55: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #56: @6 = (@6-@7) */
  w06 -= w07;
  /* #57: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #58: @5 = (@3*@5) */
  w05  = (w03*w05);
  /* #59: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #60: @4 = (@4+@5) */
  w04 += w05;
  /* #61: @17 = vertcat(@6, @4, @16, @16, @16) */
  rr=w17;
  *rr++ = w06;
  *rr++ = w04;
  /* #62: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #63: output[1][3] = @17 */
  if (res[1]) casadi_copy(w17, 2, res[1]+6);
  /* #64: {NULL, NULL, @6, @4, NULL} = vertsplit(@15) */
  w06 = wr15[2];
  w04 = wr15[3];
  /* #65: @5 = (@3*@6) */
  w05  = (w03*w06);
  /* #66: @7 = (@2*@4) */
  w07  = (w02*w04);
  /* #67: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #68: @5 = (@5-@7) */
  w05 -= w07;
  /* #69: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #70: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #71: @4 = (@1*@4) */
  w04  = (w01*w04);
  /* #72: @6 = (@6+@4) */
  w06 += w04;
  /* #73: @17 = vertcat(@5, @6, @16, @16, @16) */
  rr=w17;
  *rr++ = w05;
  *rr++ = w06;
  /* #74: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #75: output[1][4] = @17 */
  if (res[1]) casadi_copy(w17, 2, res[1]+8);
  /* #76: @18 = zeros(3x5,7nz) */
  casadi_clear(w18, 7);
  /* #77: @17 = ones(3x1,2nz) */
  casadi_fill(w17, 2, 1.);
  /* #78: {@5, @6, NULL} = vertsplit(@17) */
  w05 = w17[0];
  w06 = w17[1];
  /* #79: @17 = vertcat(@16, @16, @5, @6, @16) */
  rr=w17;
  *rr++ = w05;
  *rr++ = w06;
  /* #80: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #81: @19 = @17[:2] */
  for (rr=w19, cs=w17+0; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #82: (@18[2:6:2] = @19) */
  for (rr=w18+2, cs=w19; rr!=w18+6; rr+=2) *rr = *cs++;
  /* #83: @5 = ones(3x1,1nz) */
  w05 = 1.;
  /* #84: {NULL, NULL, @6} = vertsplit(@5) */
  w06 = w05;
  /* #85: @9 = (@9*@6) */
  for (i=0, rr=w09; i<5; ++i) (*rr++) *= w06;
  /* #86: (@18[0, 1, 3, 5, 6] = @9) */
  for (cii=casadi_s0, rr=w18, cs=w09; cii!=casadi_s0+5; ++cii, ++cs) rr[*cii] = *cs;
  /* #87: @20 = @18' */
  casadi_trans(w18,casadi_s2, w20, casadi_s1, iw);
  /* #88: @21 = project(@20) */
  casadi_project(w20, casadi_s1, w21, casadi_s3, w);
  /* #89: @22 = input[2][0] */
  wr22 = arg[2] ? arg[2] : casadi_zeros;
  /* #90: {@9, @15, @14} = horzsplit(@22) */
  wr09 = wr22;
  wr15 = wr22+5;
  wr14 = wr22+10;
  /* #91: {NULL, NULL, @6, @5, NULL} = vertsplit(@9) */
  w06 = wr09[2];
  w05 = wr09[3];
  /* #92: @4 = (@3*@6) */
  w04  = (w03*w06);
  /* #93: @7 = (@2*@5) */
  w07  = (w02*w05);
  /* #94: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #95: @4 = (@4-@7) */
  w04 -= w07;
  /* #96: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #97: @5 = (@3*@5) */
  w05  = (w03*w05);
  /* #98: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #99: @6 = (@6+@5) */
  w06 += w05;
  /* #100: @19 = vertcat(@4, @6, @16, @16, @16) */
  rr=w19;
  *rr++ = w04;
  *rr++ = w06;
  /* #101: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #102: {NULL, NULL, @4, @6, NULL} = vertsplit(@15) */
  w04 = wr15[2];
  w06 = wr15[3];
  /* #103: @5 = (@3*@4) */
  w05  = (w03*w04);
  /* #104: @7 = (@2*@6) */
  w07  = (w02*w06);
  /* #105: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #106: @5 = (@5-@7) */
  w05 -= w07;
  /* #107: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #108: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #109: @6 = (@1*@6) */
  w06  = (w01*w06);
  /* #110: @4 = (@4+@6) */
  w04 += w06;
  /* #111: @17 = vertcat(@5, @4, @16, @16, @16) */
  rr=w17;
  *rr++ = w05;
  *rr++ = w04;
  /* #112: @17 = (@0*@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #113: {NULL, NULL, @5, @4, NULL} = vertsplit(@14) */
  w05 = wr14[2];
  w04 = wr14[3];
  /* #114: @6 = (@3*@5) */
  w06  = (w03*w05);
  /* #115: @7 = (@2*@4) */
  w07  = (w02*w04);
  /* #116: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #117: @6 = (@6-@7) */
  w06 -= w07;
  /* #118: @2 = (@2*@5) */
  w02 *= w05;
  /* #119: @3 = (@3*@4) */
  w03 *= w04;
  /* #120: @1 = (@1*@3) */
  w01 *= w03;
  /* #121: @2 = (@2+@1) */
  w02 += w01;
  /* #122: @23 = vertcat(@6, @2, @16, @16, @16) */
  rr=w23;
  *rr++ = w06;
  *rr++ = w02;
  /* #123: @23 = (@0*@23) */
  for (i=0, rr=w23, cs=w23; i<2; ++i) (*rr++)  = (w00*(*cs++));
  /* #124: @24 = horzcat(@19, @17, @23) */
  rr=w24;
  for (i=0, cs=w19; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<2; ++i) *rr++ = *cs++;
  /* #125: @25 = project(@24) */
  casadi_project(w24, casadi_s4, w25, casadi_s3, w);
  /* #126: @21 = (@21+@25) */
  for (i=0, rr=w21, cs=w25; i<11; ++i) (*rr++) += (*cs++);
  /* #127: output[2][0] = @21 */
  casadi_copy(w21, 11, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int robot_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real robot_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s10;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 132;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 132*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
