/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_model_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {6, 1, 1};

/* External functions */
int y_expr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* y_expr:(i0[3])->(o0[1x10]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (y_expr(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* robot_model_cost_y_e_fun:(i0[5],i1[0],i2[0],i3[],i4[0])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, *w08=w+8, *w09=w+11;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21;
  casadi_real w22, w23;
  const casadi_real **arg1=arg+5, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #4: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #6: @2 = input[0][3] */
  w02 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #8: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @3 */
  if (res[0]) res[0][4] = w03;
  /* #10: @4 = 7.2 */
  w04 = 7.2000000000000002e+00;
  /* #11: @5 = 0 */
  w05 = 0.;
  /* #12: @3 = fmax(@3,@5) */
  w03  = casadi_fmax(w03,w05);
  /* #13: @6 = 8 */
  w06 = 8.;
  /* #14: @3 = fmin(@3,@6) */
  w03  = casadi_fmin(w03,w06);
  /* #15: @7 = (@4<=@3) */
  w07  = (w04<=w03);
  /* #16: @6 = (@3<@6) */
  w06  = (w03<w06);
  /* #17: @7 = (@7&&@6) */
  w07  = (w07&&w06);
  /* #18: @8 = vertcat(@0, @1, @2) */
  rr=w08;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  /* #19: @9 = y_expr(@8) */
  arg1[0]=w08;
  res1[0]=w09;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: @0 = @9[9] */
  for (rr=(&w00), cs=w09+9; cs!=w09+10; cs+=1) *rr++ = *cs;
  /* #21: @1 = (@7?@0:0) */
  w01  = (w07?w00:0);
  /* #22: @7 = (!@7) */
  w07 = (! w07 );
  /* #23: @2 = 6.4 */
  w02 = 6.4000000000000004e+00;
  /* #24: @6 = (@2<=@3) */
  w06  = (w02<=w03);
  /* #25: @4 = (@3<@4) */
  w04  = (w03<w04);
  /* #26: @6 = (@6&&@4) */
  w06  = (w06&&w04);
  /* #27: @4 = @9[8] */
  for (rr=(&w04), cs=w09+8; cs!=w09+9; cs+=1) *rr++ = *cs;
  /* #28: @4 = (@6?@4:0) */
  w04  = (w06?w04:0);
  /* #29: @6 = (!@6) */
  w06 = (! w06 );
  /* #30: @10 = 5.6 */
  w10 = 5.6000000000000005e+00;
  /* #31: @11 = (@10<=@3) */
  w11  = (w10<=w03);
  /* #32: @2 = (@3<@2) */
  w02  = (w03<w02);
  /* #33: @11 = (@11&&@2) */
  w11  = (w11&&w02);
  /* #34: @2 = @9[7] */
  for (rr=(&w02), cs=w09+7; cs!=w09+8; cs+=1) *rr++ = *cs;
  /* #35: @2 = (@11?@2:0) */
  w02  = (w11?w02:0);
  /* #36: @11 = (!@11) */
  w11 = (! w11 );
  /* #37: @12 = 4.8 */
  w12 = 4.8000000000000007e+00;
  /* #38: @13 = (@12<=@3) */
  w13  = (w12<=w03);
  /* #39: @10 = (@3<@10) */
  w10  = (w03<w10);
  /* #40: @13 = (@13&&@10) */
  w13  = (w13&&w10);
  /* #41: @10 = @9[6] */
  for (rr=(&w10), cs=w09+6; cs!=w09+7; cs+=1) *rr++ = *cs;
  /* #42: @10 = (@13?@10:0) */
  w10  = (w13?w10:0);
  /* #43: @13 = (!@13) */
  w13 = (! w13 );
  /* #44: @14 = 4 */
  w14 = 4.;
  /* #45: @15 = (@14<=@3) */
  w15  = (w14<=w03);
  /* #46: @12 = (@3<@12) */
  w12  = (w03<w12);
  /* #47: @15 = (@15&&@12) */
  w15  = (w15&&w12);
  /* #48: @12 = @9[5] */
  for (rr=(&w12), cs=w09+5; cs!=w09+6; cs+=1) *rr++ = *cs;
  /* #49: @12 = (@15?@12:0) */
  w12  = (w15?w12:0);
  /* #50: @15 = (!@15) */
  w15 = (! w15 );
  /* #51: @16 = 3.2 */
  w16 = 3.2000000000000002e+00;
  /* #52: @17 = (@16<=@3) */
  w17  = (w16<=w03);
  /* #53: @14 = (@3<@14) */
  w14  = (w03<w14);
  /* #54: @17 = (@17&&@14) */
  w17  = (w17&&w14);
  /* #55: @14 = @9[4] */
  for (rr=(&w14), cs=w09+4; cs!=w09+5; cs+=1) *rr++ = *cs;
  /* #56: @14 = (@17?@14:0) */
  w14  = (w17?w14:0);
  /* #57: @17 = (!@17) */
  w17 = (! w17 );
  /* #58: @18 = 2.4 */
  w18 = 2.4000000000000004e+00;
  /* #59: @19 = (@18<=@3) */
  w19  = (w18<=w03);
  /* #60: @16 = (@3<@16) */
  w16  = (w03<w16);
  /* #61: @19 = (@19&&@16) */
  w19  = (w19&&w16);
  /* #62: @16 = @9[3] */
  for (rr=(&w16), cs=w09+3; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #63: @16 = (@19?@16:0) */
  w16  = (w19?w16:0);
  /* #64: @19 = (!@19) */
  w19 = (! w19 );
  /* #65: @20 = 1.6 */
  w20 = 1.6000000000000001e+00;
  /* #66: @21 = (@20<=@3) */
  w21  = (w20<=w03);
  /* #67: @18 = (@3<@18) */
  w18  = (w03<w18);
  /* #68: @21 = (@21&&@18) */
  w21  = (w21&&w18);
  /* #69: @18 = @9[2] */
  for (rr=(&w18), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #70: @18 = (@21?@18:0) */
  w18  = (w21?w18:0);
  /* #71: @21 = (!@21) */
  w21 = (! w21 );
  /* #72: @22 = 0.8 */
  w22 = 8.0000000000000004e-01;
  /* #73: @23 = (@22<=@3) */
  w23  = (w22<=w03);
  /* #74: @20 = (@3<@20) */
  w20  = (w03<w20);
  /* #75: @23 = (@23&&@20) */
  w23  = (w23&&w20);
  /* #76: @20 = @9[1] */
  for (rr=(&w20), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #77: @20 = (@23?@20:0) */
  w20  = (w23?w20:0);
  /* #78: @23 = (!@23) */
  w23 = (! w23 );
  /* #79: @5 = (@5<=@3) */
  w05  = (w05<=w03);
  /* #80: @3 = (@3<@22) */
  w03  = (w03<w22);
  /* #81: @5 = (@5&&@3) */
  w05  = (w05&&w03);
  /* #82: @3 = @9[0] */
  for (rr=(&w03), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #83: @3 = (@5?@3:0) */
  w03  = (w05?w03:0);
  /* #84: @5 = (!@5) */
  w05 = (! w05 );
  /* #85: @5 = (@5?@0:0) */
  w05  = (w05?w00:0);
  /* #86: @3 = (@3+@5) */
  w03 += w05;
  /* #87: @23 = (@23?@3:0) */
  w23  = (w23?w03:0);
  /* #88: @20 = (@20+@23) */
  w20 += w23;
  /* #89: @21 = (@21?@20:0) */
  w21  = (w21?w20:0);
  /* #90: @18 = (@18+@21) */
  w18 += w21;
  /* #91: @19 = (@19?@18:0) */
  w19  = (w19?w18:0);
  /* #92: @16 = (@16+@19) */
  w16 += w19;
  /* #93: @17 = (@17?@16:0) */
  w17  = (w17?w16:0);
  /* #94: @14 = (@14+@17) */
  w14 += w17;
  /* #95: @15 = (@15?@14:0) */
  w15  = (w15?w14:0);
  /* #96: @12 = (@12+@15) */
  w12 += w15;
  /* #97: @13 = (@13?@12:0) */
  w13  = (w13?w12:0);
  /* #98: @10 = (@10+@13) */
  w10 += w13;
  /* #99: @11 = (@11?@10:0) */
  w11  = (w11?w10:0);
  /* #100: @2 = (@2+@11) */
  w02 += w11;
  /* #101: @6 = (@6?@2:0) */
  w06  = (w06?w02:0);
  /* #102: @4 = (@4+@6) */
  w04 += w06;
  /* #103: @7 = (@7?@4:0) */
  w07  = (w07?w04:0);
  /* #104: @1 = (@1+@7) */
  w01 += w07;
  /* #105: output[0][5] = @1 */
  if (res[0]) res[0][5] = w01;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real robot_model_cost_y_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 35;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 35*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
