/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_model_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[36] = 
  {10, 3, 0, 10, 20, 30, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9};
static const casadi_int casadi_s1[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s2[3] = {0, 2, 5};
static const casadi_int casadi_s3[3] = {5, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};
static const casadi_int casadi_s6[3] = {6, 1, 1};
static const casadi_int casadi_s7[18] = 
  {5, 6, 0, 1, 2, 3, 4, 5,
  9, 0, 1, 2, 3, 4, 0, 1,
  3, 4};
static const casadi_int casadi_s8[3] = {6, 0, 1};

/* External functions */
int jac_y_expr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int y_expr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* y_expr:(i0[3])->(o0[1x10]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (y_expr(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_y_expr:(i0[3],out_o0[1x10,0nz])->(jac_o0_i0[10x3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_y_expr(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* robot_model_cost_y_e_fun_jac_ut_xt:(i0[5],i1[0],i2[0],i3[],i4[0])->(o0[6],o1[5x6,9nz],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+3, *rr, w00, w01, w02, w03, w04, w05, w06, w07, *w08=w+18, *w09=w+21;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21;
  casadi_real w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+54;
  casadi_real *w34=w+63, *w36=w+65, *w38=w+95, *w39=w+125, *w40=w+135, w41, w42, w43, w44, *w45=w+149, *w46=w+152;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #4: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #6: @2 = input[0][3] */
  w02 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @2 */
  if (res[0]) res[0][3] = w02;
  /* #8: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @3 */
  if (res[0]) res[0][4] = w03;
  /* #10: @4 = 7.2 */
  w04 = 7.2000000000000002e+00;
  /* #11: @5 = 0 */
  w05 = 0.;
  /* #12: @3 = fmax(@3,@5) */
  w03  = casadi_fmax(w03,w05);
  /* #13: @6 = 8 */
  w06 = 8.;
  /* #14: @3 = fmin(@3,@6) */
  w03  = casadi_fmin(w03,w06);
  /* #15: @7 = (@4<=@3) */
  w07  = (w04<=w03);
  /* #16: @6 = (@3<@6) */
  w06  = (w03<w06);
  /* #17: @7 = (@7&&@6) */
  w07  = (w07&&w06);
  /* #18: @8 = vertcat(@0, @1, @2) */
  rr=w08;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  /* #19: @9 = y_expr(@8) */
  arg1[0]=w08;
  res1[0]=w09;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: @0 = @9[9] */
  for (rr=(&w00), cs=w09+9; cs!=w09+10; cs+=1) *rr++ = *cs;
  /* #21: @1 = (@7?@0:0) */
  w01  = (w07?w00:0);
  /* #22: @2 = (!@7) */
  w02 = (! w07 );
  /* #23: @6 = 6.4 */
  w06 = 6.4000000000000004e+00;
  /* #24: @10 = (@6<=@3) */
  w10  = (w06<=w03);
  /* #25: @4 = (@3<@4) */
  w04  = (w03<w04);
  /* #26: @10 = (@10&&@4) */
  w10  = (w10&&w04);
  /* #27: @4 = @9[8] */
  for (rr=(&w04), cs=w09+8; cs!=w09+9; cs+=1) *rr++ = *cs;
  /* #28: @4 = (@10?@4:0) */
  w04  = (w10?w04:0);
  /* #29: @11 = (!@10) */
  w11 = (! w10 );
  /* #30: @12 = 5.6 */
  w12 = 5.6000000000000005e+00;
  /* #31: @13 = (@12<=@3) */
  w13  = (w12<=w03);
  /* #32: @6 = (@3<@6) */
  w06  = (w03<w06);
  /* #33: @13 = (@13&&@6) */
  w13  = (w13&&w06);
  /* #34: @6 = @9[7] */
  for (rr=(&w06), cs=w09+7; cs!=w09+8; cs+=1) *rr++ = *cs;
  /* #35: @6 = (@13?@6:0) */
  w06  = (w13?w06:0);
  /* #36: @14 = (!@13) */
  w14 = (! w13 );
  /* #37: @15 = 4.8 */
  w15 = 4.8000000000000007e+00;
  /* #38: @16 = (@15<=@3) */
  w16  = (w15<=w03);
  /* #39: @12 = (@3<@12) */
  w12  = (w03<w12);
  /* #40: @16 = (@16&&@12) */
  w16  = (w16&&w12);
  /* #41: @12 = @9[6] */
  for (rr=(&w12), cs=w09+6; cs!=w09+7; cs+=1) *rr++ = *cs;
  /* #42: @12 = (@16?@12:0) */
  w12  = (w16?w12:0);
  /* #43: @17 = (!@16) */
  w17 = (! w16 );
  /* #44: @18 = 4 */
  w18 = 4.;
  /* #45: @19 = (@18<=@3) */
  w19  = (w18<=w03);
  /* #46: @15 = (@3<@15) */
  w15  = (w03<w15);
  /* #47: @19 = (@19&&@15) */
  w19  = (w19&&w15);
  /* #48: @15 = @9[5] */
  for (rr=(&w15), cs=w09+5; cs!=w09+6; cs+=1) *rr++ = *cs;
  /* #49: @15 = (@19?@15:0) */
  w15  = (w19?w15:0);
  /* #50: @20 = (!@19) */
  w20 = (! w19 );
  /* #51: @21 = 3.2 */
  w21 = 3.2000000000000002e+00;
  /* #52: @22 = (@21<=@3) */
  w22  = (w21<=w03);
  /* #53: @18 = (@3<@18) */
  w18  = (w03<w18);
  /* #54: @22 = (@22&&@18) */
  w22  = (w22&&w18);
  /* #55: @18 = @9[4] */
  for (rr=(&w18), cs=w09+4; cs!=w09+5; cs+=1) *rr++ = *cs;
  /* #56: @18 = (@22?@18:0) */
  w18  = (w22?w18:0);
  /* #57: @23 = (!@22) */
  w23 = (! w22 );
  /* #58: @24 = 2.4 */
  w24 = 2.4000000000000004e+00;
  /* #59: @25 = (@24<=@3) */
  w25  = (w24<=w03);
  /* #60: @21 = (@3<@21) */
  w21  = (w03<w21);
  /* #61: @25 = (@25&&@21) */
  w25  = (w25&&w21);
  /* #62: @21 = @9[3] */
  for (rr=(&w21), cs=w09+3; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #63: @21 = (@25?@21:0) */
  w21  = (w25?w21:0);
  /* #64: @26 = (!@25) */
  w26 = (! w25 );
  /* #65: @27 = 1.6 */
  w27 = 1.6000000000000001e+00;
  /* #66: @28 = (@27<=@3) */
  w28  = (w27<=w03);
  /* #67: @24 = (@3<@24) */
  w24  = (w03<w24);
  /* #68: @28 = (@28&&@24) */
  w28  = (w28&&w24);
  /* #69: @24 = @9[2] */
  for (rr=(&w24), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #70: @24 = (@28?@24:0) */
  w24  = (w28?w24:0);
  /* #71: @29 = (!@28) */
  w29 = (! w28 );
  /* #72: @30 = 0.8 */
  w30 = 8.0000000000000004e-01;
  /* #73: @31 = (@30<=@3) */
  w31  = (w30<=w03);
  /* #74: @27 = (@3<@27) */
  w27  = (w03<w27);
  /* #75: @31 = (@31&&@27) */
  w31  = (w31&&w27);
  /* #76: @27 = @9[1] */
  for (rr=(&w27), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #77: @27 = (@31?@27:0) */
  w27  = (w31?w27:0);
  /* #78: @32 = (!@31) */
  w32 = (! w31 );
  /* #79: @5 = (@5<=@3) */
  w05  = (w05<=w03);
  /* #80: @3 = (@3<@30) */
  w03  = (w03<w30);
  /* #81: @5 = (@5&&@3) */
  w05  = (w05&&w03);
  /* #82: @3 = @9[0] */
  for (rr=(&w03), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #83: @3 = (@5?@3:0) */
  w03  = (w05?w03:0);
  /* #84: @30 = (!@5) */
  w30 = (! w05 );
  /* #85: @0 = (@30?@0:0) */
  w00  = (w30?w00:0);
  /* #86: @3 = (@3+@0) */
  w03 += w00;
  /* #87: @3 = (@32?@3:0) */
  w03  = (w32?w03:0);
  /* #88: @27 = (@27+@3) */
  w27 += w03;
  /* #89: @27 = (@29?@27:0) */
  w27  = (w29?w27:0);
  /* #90: @24 = (@24+@27) */
  w24 += w27;
  /* #91: @24 = (@26?@24:0) */
  w24  = (w26?w24:0);
  /* #92: @21 = (@21+@24) */
  w21 += w24;
  /* #93: @21 = (@23?@21:0) */
  w21  = (w23?w21:0);
  /* #94: @18 = (@18+@21) */
  w18 += w21;
  /* #95: @18 = (@20?@18:0) */
  w18  = (w20?w18:0);
  /* #96: @15 = (@15+@18) */
  w15 += w18;
  /* #97: @15 = (@17?@15:0) */
  w15  = (w17?w15:0);
  /* #98: @12 = (@12+@15) */
  w12 += w15;
  /* #99: @12 = (@14?@12:0) */
  w12  = (w14?w12:0);
  /* #100: @6 = (@6+@12) */
  w06 += w12;
  /* #101: @6 = (@11?@6:0) */
  w06  = (w11?w06:0);
  /* #102: @4 = (@4+@6) */
  w04 += w06;
  /* #103: @4 = (@2?@4:0) */
  w04  = (w02?w04:0);
  /* #104: @1 = (@1+@4) */
  w01 += w04;
  /* #105: output[0][5] = @1 */
  if (res[0]) res[0][5] = w01;
  /* #106: @33 = zeros(5x6,9nz) */
  casadi_clear(w33, 9);
  /* #107: @34 = ones(5x1,2nz) */
  casadi_fill(w34, 2, 1.);
  /* #108: {@1, NULL, @4, NULL, NULL} = vertsplit(@34) */
  w01 = w34[0];
  w04 = w34[1];
  /* #109: @35 = 00 */
  /* #110: @36 = zeros(10x3) */
  casadi_clear(w36, 30);
  /* #111: @37 = zeros(1x10,0nz) */
  /* #112: @38 = jac_y_expr(@8, @37) */
  arg1[0]=w08;
  arg1[1]=0;
  res1[0]=w38;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #113: @6 = vertcat(@1, @35, @35) */
  rr=(&w06);
  *rr++ = w01;
  /* #114: @12 = ones(5x1,1nz) */
  w12 = 1.;
  /* #115: {NULL, @15, NULL, NULL, NULL} = vertsplit(@12) */
  w15 = w12;
  /* #116: @12 = vertcat(@35, @15, @35) */
  rr=(&w12);
  *rr++ = w15;
  /* #117: @18 = ones(5x1,1nz) */
  w18 = 1.;
  /* #118: {NULL, NULL, NULL, @21, NULL} = vertsplit(@18) */
  w21 = w18;
  /* #119: @18 = vertcat(@35, @35, @21) */
  rr=(&w18);
  *rr++ = w21;
  /* #120: @8 = horzcat(@6, @12, @18) */
  rr=w08;
  *rr++ = w06;
  *rr++ = w12;
  *rr++ = w18;
  /* #121: @36 = mac(@38,@8,@36) */
  casadi_mtimes(w38, casadi_s0, w08, casadi_s1, w36, casadi_s0, w, 0);
  /* #122: {@9, @39, @40} = horzsplit(@36) */
  casadi_copy(w36, 10, w09);
  casadi_copy(w36+10, 10, w39);
  casadi_copy(w36+20, 10, w40);
  /* #123: @9 = @9' */
  /* #124: @6 = @9[9] */
  for (rr=(&w06), cs=w09+9; cs!=w09+10; cs+=1) *rr++ = *cs;
  /* #125: @12 = (@7?@6:0) */
  w12  = (w07?w06:0);
  /* #126: @18 = @9[8] */
  for (rr=(&w18), cs=w09+8; cs!=w09+9; cs+=1) *rr++ = *cs;
  /* #127: @18 = (@10?@18:0) */
  w18  = (w10?w18:0);
  /* #128: @24 = @9[7] */
  for (rr=(&w24), cs=w09+7; cs!=w09+8; cs+=1) *rr++ = *cs;
  /* #129: @24 = (@13?@24:0) */
  w24  = (w13?w24:0);
  /* #130: @27 = @9[6] */
  for (rr=(&w27), cs=w09+6; cs!=w09+7; cs+=1) *rr++ = *cs;
  /* #131: @27 = (@16?@27:0) */
  w27  = (w16?w27:0);
  /* #132: @3 = @9[5] */
  for (rr=(&w03), cs=w09+5; cs!=w09+6; cs+=1) *rr++ = *cs;
  /* #133: @3 = (@19?@3:0) */
  w03  = (w19?w03:0);
  /* #134: @0 = @9[4] */
  for (rr=(&w00), cs=w09+4; cs!=w09+5; cs+=1) *rr++ = *cs;
  /* #135: @0 = (@22?@0:0) */
  w00  = (w22?w00:0);
  /* #136: @41 = @9[3] */
  for (rr=(&w41), cs=w09+3; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #137: @41 = (@25?@41:0) */
  w41  = (w25?w41:0);
  /* #138: @42 = @9[2] */
  for (rr=(&w42), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #139: @42 = (@28?@42:0) */
  w42  = (w28?w42:0);
  /* #140: @43 = @9[1] */
  for (rr=(&w43), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #141: @43 = (@31?@43:0) */
  w43  = (w31?w43:0);
  /* #142: @44 = @9[0] */
  for (rr=(&w44), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #143: @44 = (@5?@44:0) */
  w44  = (w05?w44:0);
  /* #144: @6 = (@30?@6:0) */
  w06  = (w30?w06:0);
  /* #145: @44 = (@44+@6) */
  w44 += w06;
  /* #146: @44 = (@32?@44:0) */
  w44  = (w32?w44:0);
  /* #147: @43 = (@43+@44) */
  w43 += w44;
  /* #148: @43 = (@29?@43:0) */
  w43  = (w29?w43:0);
  /* #149: @42 = (@42+@43) */
  w42 += w43;
  /* #150: @42 = (@26?@42:0) */
  w42  = (w26?w42:0);
  /* #151: @41 = (@41+@42) */
  w41 += w42;
  /* #152: @41 = (@23?@41:0) */
  w41  = (w23?w41:0);
  /* #153: @0 = (@0+@41) */
  w00 += w41;
  /* #154: @0 = (@20?@0:0) */
  w00  = (w20?w00:0);
  /* #155: @3 = (@3+@0) */
  w03 += w00;
  /* #156: @3 = (@17?@3:0) */
  w03  = (w17?w03:0);
  /* #157: @27 = (@27+@3) */
  w27 += w03;
  /* #158: @27 = (@14?@27:0) */
  w27  = (w14?w27:0);
  /* #159: @24 = (@24+@27) */
  w24 += w27;
  /* #160: @24 = (@11?@24:0) */
  w24  = (w11?w24:0);
  /* #161: @18 = (@18+@24) */
  w18 += w24;
  /* #162: @18 = (@2?@18:0) */
  w18  = (w02?w18:0);
  /* #163: @12 = (@12+@18) */
  w12 += w18;
  /* #164: @8 = vertcat(@1, @35, @4, @35, @35, @12) */
  rr=w08;
  *rr++ = w01;
  *rr++ = w04;
  *rr++ = w12;
  /* #165: @45 = @8[:3] */
  for (rr=w45, cs=w08+0; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #166: (@33[0, 2, 5] = @45) */
  for (cii=casadi_s2, rr=w33, cs=w45; cii!=casadi_s2+3; ++cii, ++cs) rr[*cii] = *cs;
  /* #167: @39 = @39' */
  /* #168: @1 = @39[9] */
  for (rr=(&w01), cs=w39+9; cs!=w39+10; cs+=1) *rr++ = *cs;
  /* #169: @4 = (@7?@1:0) */
  w04  = (w07?w01:0);
  /* #170: @12 = @39[8] */
  for (rr=(&w12), cs=w39+8; cs!=w39+9; cs+=1) *rr++ = *cs;
  /* #171: @12 = (@10?@12:0) */
  w12  = (w10?w12:0);
  /* #172: @18 = @39[7] */
  for (rr=(&w18), cs=w39+7; cs!=w39+8; cs+=1) *rr++ = *cs;
  /* #173: @18 = (@13?@18:0) */
  w18  = (w13?w18:0);
  /* #174: @24 = @39[6] */
  for (rr=(&w24), cs=w39+6; cs!=w39+7; cs+=1) *rr++ = *cs;
  /* #175: @24 = (@16?@24:0) */
  w24  = (w16?w24:0);
  /* #176: @27 = @39[5] */
  for (rr=(&w27), cs=w39+5; cs!=w39+6; cs+=1) *rr++ = *cs;
  /* #177: @27 = (@19?@27:0) */
  w27  = (w19?w27:0);
  /* #178: @3 = @39[4] */
  for (rr=(&w03), cs=w39+4; cs!=w39+5; cs+=1) *rr++ = *cs;
  /* #179: @3 = (@22?@3:0) */
  w03  = (w22?w03:0);
  /* #180: @0 = @39[3] */
  for (rr=(&w00), cs=w39+3; cs!=w39+4; cs+=1) *rr++ = *cs;
  /* #181: @0 = (@25?@0:0) */
  w00  = (w25?w00:0);
  /* #182: @41 = @39[2] */
  for (rr=(&w41), cs=w39+2; cs!=w39+3; cs+=1) *rr++ = *cs;
  /* #183: @41 = (@28?@41:0) */
  w41  = (w28?w41:0);
  /* #184: @42 = @39[1] */
  for (rr=(&w42), cs=w39+1; cs!=w39+2; cs+=1) *rr++ = *cs;
  /* #185: @42 = (@31?@42:0) */
  w42  = (w31?w42:0);
  /* #186: @43 = @39[0] */
  for (rr=(&w43), cs=w39+0; cs!=w39+1; cs+=1) *rr++ = *cs;
  /* #187: @43 = (@5?@43:0) */
  w43  = (w05?w43:0);
  /* #188: @1 = (@30?@1:0) */
  w01  = (w30?w01:0);
  /* #189: @43 = (@43+@1) */
  w43 += w01;
  /* #190: @43 = (@32?@43:0) */
  w43  = (w32?w43:0);
  /* #191: @42 = (@42+@43) */
  w42 += w43;
  /* #192: @42 = (@29?@42:0) */
  w42  = (w29?w42:0);
  /* #193: @41 = (@41+@42) */
  w41 += w42;
  /* #194: @41 = (@26?@41:0) */
  w41  = (w26?w41:0);
  /* #195: @0 = (@0+@41) */
  w00 += w41;
  /* #196: @0 = (@23?@0:0) */
  w00  = (w23?w00:0);
  /* #197: @3 = (@3+@0) */
  w03 += w00;
  /* #198: @3 = (@20?@3:0) */
  w03  = (w20?w03:0);
  /* #199: @27 = (@27+@3) */
  w27 += w03;
  /* #200: @27 = (@17?@27:0) */
  w27  = (w17?w27:0);
  /* #201: @24 = (@24+@27) */
  w24 += w27;
  /* #202: @24 = (@14?@24:0) */
  w24  = (w14?w24:0);
  /* #203: @18 = (@18+@24) */
  w18 += w24;
  /* #204: @18 = (@11?@18:0) */
  w18  = (w11?w18:0);
  /* #205: @12 = (@12+@18) */
  w12 += w18;
  /* #206: @12 = (@2?@12:0) */
  w12  = (w02?w12:0);
  /* #207: @4 = (@4+@12) */
  w04 += w12;
  /* #208: @34 = vertcat(@35, @15, @35, @35, @35, @4) */
  rr=w34;
  *rr++ = w15;
  *rr++ = w04;
  /* #209: @46 = @34[:2] */
  for (rr=w46, cs=w34+0; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #210: (@33[1:11:5] = @46) */
  for (rr=w33+1, cs=w46; rr!=w33+11; rr+=5) *rr = *cs++;
  /* #211: @40 = @40' */
  /* #212: @15 = @40[9] */
  for (rr=(&w15), cs=w40+9; cs!=w40+10; cs+=1) *rr++ = *cs;
  /* #213: @7 = (@7?@15:0) */
  w07  = (w07?w15:0);
  /* #214: @4 = @40[8] */
  for (rr=(&w04), cs=w40+8; cs!=w40+9; cs+=1) *rr++ = *cs;
  /* #215: @10 = (@10?@4:0) */
  w10  = (w10?w04:0);
  /* #216: @4 = @40[7] */
  for (rr=(&w04), cs=w40+7; cs!=w40+8; cs+=1) *rr++ = *cs;
  /* #217: @13 = (@13?@4:0) */
  w13  = (w13?w04:0);
  /* #218: @4 = @40[6] */
  for (rr=(&w04), cs=w40+6; cs!=w40+7; cs+=1) *rr++ = *cs;
  /* #219: @16 = (@16?@4:0) */
  w16  = (w16?w04:0);
  /* #220: @4 = @40[5] */
  for (rr=(&w04), cs=w40+5; cs!=w40+6; cs+=1) *rr++ = *cs;
  /* #221: @19 = (@19?@4:0) */
  w19  = (w19?w04:0);
  /* #222: @4 = @40[4] */
  for (rr=(&w04), cs=w40+4; cs!=w40+5; cs+=1) *rr++ = *cs;
  /* #223: @22 = (@22?@4:0) */
  w22  = (w22?w04:0);
  /* #224: @4 = @40[3] */
  for (rr=(&w04), cs=w40+3; cs!=w40+4; cs+=1) *rr++ = *cs;
  /* #225: @25 = (@25?@4:0) */
  w25  = (w25?w04:0);
  /* #226: @4 = @40[2] */
  for (rr=(&w04), cs=w40+2; cs!=w40+3; cs+=1) *rr++ = *cs;
  /* #227: @28 = (@28?@4:0) */
  w28  = (w28?w04:0);
  /* #228: @4 = @40[1] */
  for (rr=(&w04), cs=w40+1; cs!=w40+2; cs+=1) *rr++ = *cs;
  /* #229: @31 = (@31?@4:0) */
  w31  = (w31?w04:0);
  /* #230: @4 = @40[0] */
  for (rr=(&w04), cs=w40+0; cs!=w40+1; cs+=1) *rr++ = *cs;
  /* #231: @5 = (@5?@4:0) */
  w05  = (w05?w04:0);
  /* #232: @30 = (@30?@15:0) */
  w30  = (w30?w15:0);
  /* #233: @5 = (@5+@30) */
  w05 += w30;
  /* #234: @32 = (@32?@5:0) */
  w32  = (w32?w05:0);
  /* #235: @31 = (@31+@32) */
  w31 += w32;
  /* #236: @29 = (@29?@31:0) */
  w29  = (w29?w31:0);
  /* #237: @28 = (@28+@29) */
  w28 += w29;
  /* #238: @26 = (@26?@28:0) */
  w26  = (w26?w28:0);
  /* #239: @25 = (@25+@26) */
  w25 += w26;
  /* #240: @23 = (@23?@25:0) */
  w23  = (w23?w25:0);
  /* #241: @22 = (@22+@23) */
  w22 += w23;
  /* #242: @20 = (@20?@22:0) */
  w20  = (w20?w22:0);
  /* #243: @19 = (@19+@20) */
  w19 += w20;
  /* #244: @17 = (@17?@19:0) */
  w17  = (w17?w19:0);
  /* #245: @16 = (@16+@17) */
  w16 += w17;
  /* #246: @14 = (@14?@16:0) */
  w14  = (w14?w16:0);
  /* #247: @13 = (@13+@14) */
  w13 += w14;
  /* #248: @11 = (@11?@13:0) */
  w11  = (w11?w13:0);
  /* #249: @10 = (@10+@11) */
  w10 += w11;
  /* #250: @2 = (@2?@10:0) */
  w02  = (w02?w10:0);
  /* #251: @7 = (@7+@2) */
  w07 += w02;
  /* #252: @46 = vertcat(@35, @35, @35, @21, @35, @7) */
  rr=w46;
  *rr++ = w21;
  *rr++ = w07;
  /* #253: @34 = @46[:2] */
  for (rr=w34, cs=w46+0; cs!=w46+2; cs+=1) *rr++ = *cs;
  /* #254: (@33[3:11:4] = @34) */
  for (rr=w33+3, cs=w34; rr!=w33+11; rr+=4) *rr = *cs++;
  /* #255: @21 = ones(5x1,1nz) */
  w21 = 1.;
  /* #256: {NULL, NULL, NULL, NULL, @7} = vertsplit(@21) */
  w07 = w21;
  /* #257: (@33[4] = @7) */
  for (rr=w33+4, cs=(&w07); rr!=w33+5; rr+=1) *rr = *cs++;
  /* #258: output[1][0] = @33 */
  casadi_copy(w33, 9, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real robot_model_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 154;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 154*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
