/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_model_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s1[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s2[20] = 
  {5, 5, 0, 3, 6, 6, 9, 12,
  0, 1, 3, 0, 1, 3, 0, 1,
  3, 0, 1, 3};
static const casadi_int casadi_s3[20] = 
  {5, 5, 0, 4, 8, 8, 12, 12,
  0, 1, 3, 4, 0, 1, 3, 4,
  0, 1, 3, 4};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {0, 1, 1};
static const casadi_int casadi_s6[3] = {6, 1, 1};
static const casadi_int casadi_s7[3] = {0, 0, 1};

/* External functions */
int jac_adj1_y_expr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* jac_adj1_y_expr:(i0[3],out_o0[1x10,0nz],adj_o0[1x10],out_adj_i0[3x1,0nz])->(jac_adj_i0_i0[3x3],jac_adj_i0_out_o0[3x10,0nz],jac_adj_i0_adj_o0[3x10]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_adj1_y_expr(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* robot_model_cost_y_e_hess:(i0[5],i1[0],i2[0],i3[6],i4[],i5[0])->(o0[5x5,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *w00=w+3, *w01=w+15, w02, w03, w04, *w05=w+27, *w07=w+30, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, *w26=w+58, *w28=w+64, *w29=w+73, *w30=w+75, *w31=w+78, *w32=w+81, *w33=w+84;
  const casadi_real **arg1=arg+6, *cs;
  /* #0: @0 = zeros(5x5,12nz) */
  casadi_clear(w00, 12);
  /* #1: @1 = zeros(3x3) */
  casadi_clear(w01, 9);
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][3] */
  w04 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = vertcat(@2, @3, @4) */
  rr=w05;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  /* #6: @6 = zeros(1x10,0nz) */
  /* #7: @7 = zeros(1x10) */
  casadi_clear(w07, 10);
  /* #8: @2 = 0 */
  w02 = 0.;
  /* #9: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #10: @3 = fmax(@3,@2) */
  w03  = casadi_fmax(w03,w02);
  /* #11: @4 = 9 */
  w04 = 9.;
  /* #12: @3 = fmin(@3,@4) */
  w03  = casadi_fmin(w03,w04);
  /* #13: @2 = (@2<=@3) */
  w02  = (w02<=w03);
  /* #14: @8 = 0.9 */
  w08 = 9.0000000000000002e-01;
  /* #15: @9 = (@3<@8) */
  w09  = (w03<w08);
  /* #16: @2 = (@2&&@9) */
  w02  = (w02&&w09);
  /* #17: @9 = (!@2) */
  w09 = (! w02 );
  /* #18: @8 = (@8<=@3) */
  w08  = (w08<=w03);
  /* #19: @10 = 1.8 */
  w10 = 1.8000000000000000e+00;
  /* #20: @11 = (@3<@10) */
  w11  = (w03<w10);
  /* #21: @8 = (@8&&@11) */
  w08  = (w08&&w11);
  /* #22: @11 = (!@8) */
  w11 = (! w08 );
  /* #23: @10 = (@10<=@3) */
  w10  = (w10<=w03);
  /* #24: @12 = 2.7 */
  w12 = 2.7000000000000002e+00;
  /* #25: @13 = (@3<@12) */
  w13  = (w03<w12);
  /* #26: @10 = (@10&&@13) */
  w10  = (w10&&w13);
  /* #27: @13 = (!@10) */
  w13 = (! w10 );
  /* #28: @12 = (@12<=@3) */
  w12  = (w12<=w03);
  /* #29: @14 = 3.6 */
  w14 = 3.6000000000000001e+00;
  /* #30: @15 = (@3<@14) */
  w15  = (w03<w14);
  /* #31: @12 = (@12&&@15) */
  w12  = (w12&&w15);
  /* #32: @15 = (!@12) */
  w15 = (! w12 );
  /* #33: @14 = (@14<=@3) */
  w14  = (w14<=w03);
  /* #34: @16 = 4.5 */
  w16 = 4.5000000000000000e+00;
  /* #35: @17 = (@3<@16) */
  w17  = (w03<w16);
  /* #36: @14 = (@14&&@17) */
  w14  = (w14&&w17);
  /* #37: @17 = (!@14) */
  w17 = (! w14 );
  /* #38: @16 = (@16<=@3) */
  w16  = (w16<=w03);
  /* #39: @18 = 5.4 */
  w18 = 5.4000000000000004e+00;
  /* #40: @19 = (@3<@18) */
  w19  = (w03<w18);
  /* #41: @16 = (@16&&@19) */
  w16  = (w16&&w19);
  /* #42: @19 = (!@16) */
  w19 = (! w16 );
  /* #43: @18 = (@18<=@3) */
  w18  = (w18<=w03);
  /* #44: @20 = 6.3 */
  w20 = 6.2999999999999998e+00;
  /* #45: @21 = (@3<@20) */
  w21  = (w03<w20);
  /* #46: @18 = (@18&&@21) */
  w18  = (w18&&w21);
  /* #47: @21 = (!@18) */
  w21 = (! w18 );
  /* #48: @20 = (@20<=@3) */
  w20  = (w20<=w03);
  /* #49: @22 = 7.2 */
  w22 = 7.2000000000000002e+00;
  /* #50: @23 = (@3<@22) */
  w23  = (w03<w22);
  /* #51: @20 = (@20&&@23) */
  w20  = (w20&&w23);
  /* #52: @23 = (!@20) */
  w23 = (! w20 );
  /* #53: @22 = (@22<=@3) */
  w22  = (w22<=w03);
  /* #54: @24 = 8.1 */
  w24 = 8.0999999999999996e+00;
  /* #55: @25 = (@3<@24) */
  w25  = (w03<w24);
  /* #56: @22 = (@22&&@25) */
  w22  = (w22&&w25);
  /* #57: @25 = (!@22) */
  w25 = (! w22 );
  /* #58: @24 = (@24<=@3) */
  w24  = (w24<=w03);
  /* #59: @3 = (@3<@4) */
  w03  = (w03<w04);
  /* #60: @24 = (@24&&@3) */
  w24  = (w24&&w03);
  /* #61: @3 = (!@24) */
  w03 = (! w24 );
  /* #62: @26 = input[3][0] */
  casadi_copy(arg[3], 6, w26);
  /* #63: {NULL, NULL, NULL, NULL, NULL, @4} = vertsplit(@26) */
  w04 = w26[5];
  /* #64: @3 = (@3?@4:0) */
  w03  = (w03?w04:0);
  /* #65: @25 = (@25?@3:0) */
  w25  = (w25?w03:0);
  /* #66: @23 = (@23?@25:0) */
  w23  = (w23?w25:0);
  /* #67: @21 = (@21?@23:0) */
  w21  = (w21?w23:0);
  /* #68: @19 = (@19?@21:0) */
  w19  = (w19?w21:0);
  /* #69: @17 = (@17?@19:0) */
  w17  = (w17?w19:0);
  /* #70: @15 = (@15?@17:0) */
  w15  = (w15?w17:0);
  /* #71: @13 = (@13?@15:0) */
  w13  = (w13?w15:0);
  /* #72: @11 = (@11?@13:0) */
  w11  = (w11?w13:0);
  /* #73: @9 = (@9?@11:0) */
  w09  = (w09?w11:0);
  /* #74: (@7[9] += @9) */
  for (rr=w07+9, cs=(&w09); rr!=w07+10; rr+=1) *rr += *cs++;
  /* #75: @2 = (@2?@11:0) */
  w02  = (w02?w11:0);
  /* #76: (@7[0] += @2) */
  for (rr=w07+0, cs=(&w02); rr!=w07+1; rr+=1) *rr += *cs++;
  /* #77: @8 = (@8?@13:0) */
  w08  = (w08?w13:0);
  /* #78: (@7[1] += @8) */
  for (rr=w07+1, cs=(&w08); rr!=w07+2; rr+=1) *rr += *cs++;
  /* #79: @10 = (@10?@15:0) */
  w10  = (w10?w15:0);
  /* #80: (@7[2] += @10) */
  for (rr=w07+2, cs=(&w10); rr!=w07+3; rr+=1) *rr += *cs++;
  /* #81: @12 = (@12?@17:0) */
  w12  = (w12?w17:0);
  /* #82: (@7[3] += @12) */
  for (rr=w07+3, cs=(&w12); rr!=w07+4; rr+=1) *rr += *cs++;
  /* #83: @14 = (@14?@19:0) */
  w14  = (w14?w19:0);
  /* #84: (@7[4] += @14) */
  for (rr=w07+4, cs=(&w14); rr!=w07+5; rr+=1) *rr += *cs++;
  /* #85: @16 = (@16?@21:0) */
  w16  = (w16?w21:0);
  /* #86: (@7[5] += @16) */
  for (rr=w07+5, cs=(&w16); rr!=w07+6; rr+=1) *rr += *cs++;
  /* #87: @18 = (@18?@23:0) */
  w18  = (w18?w23:0);
  /* #88: (@7[6] += @18) */
  for (rr=w07+6, cs=(&w18); rr!=w07+7; rr+=1) *rr += *cs++;
  /* #89: @20 = (@20?@25:0) */
  w20  = (w20?w25:0);
  /* #90: (@7[7] += @20) */
  for (rr=w07+7, cs=(&w20); rr!=w07+8; rr+=1) *rr += *cs++;
  /* #91: @22 = (@22?@3:0) */
  w22  = (w22?w03:0);
  /* #92: (@7[8] += @22) */
  for (rr=w07+8, cs=(&w22); rr!=w07+9; rr+=1) *rr += *cs++;
  /* #93: @24 = (@24?@4:0) */
  w24  = (w24?w04:0);
  /* #94: (@7[9] += @24) */
  for (rr=w07+9, cs=(&w24); rr!=w07+10; rr+=1) *rr += *cs++;
  /* #95: @27 = zeros(3x1,0nz) */
  /* #96: {@28, NULL, NULL} = jac_adj1_y_expr(@5, @6, @7, @27) */
  arg1[0]=w05;
  arg1[1]=0;
  arg1[2]=w07;
  arg1[3]=0;
  res1[0]=w28;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #97: @29 = ones(5x1,2nz) */
  casadi_fill(w29, 2, 1.);
  /* #98: {@24, NULL, NULL, NULL, NULL} = vertsplit(@29) */
  w24 = w29[0];
  /* #99: @6 = 00 */
  /* #100: @4 = vertcat(@24, @6, @6) */
  rr=(&w04);
  *rr++ = w24;
  /* #101: @24 = ones(5x1,1nz) */
  w24 = 1.;
  /* #102: {NULL, @22, NULL, NULL, NULL} = vertsplit(@24) */
  w22 = w24;
  /* #103: @24 = vertcat(@6, @22, @6) */
  rr=(&w24);
  *rr++ = w22;
  /* #104: @22 = ones(5x1,1nz) */
  w22 = 1.;
  /* #105: {NULL, NULL, NULL, @3, NULL} = vertsplit(@22) */
  w03 = w22;
  /* #106: @22 = vertcat(@6, @6, @3) */
  rr=(&w22);
  *rr++ = w03;
  /* #107: @5 = horzcat(@4, @24, @22) */
  rr=w05;
  *rr++ = w04;
  *rr++ = w24;
  *rr++ = w22;
  /* #108: @1 = mac(@28,@5,@1) */
  casadi_mtimes(w28, casadi_s0, w05, casadi_s1, w01, casadi_s0, w, 0);
  /* #109: {@5, @30, @31} = horzsplit(@1) */
  casadi_copy(w01, 3, w05);
  casadi_copy(w01+3, 3, w30);
  casadi_copy(w01+6, 3, w31);
  /* #110: {@4, @24, @22} = vertsplit(@5) */
  w04 = w05[0];
  w24 = w05[1];
  w22 = w05[2];
  /* #111: @5 = vertcat(@4, @24, @6, @22, @6) */
  rr=w05;
  *rr++ = w04;
  *rr++ = w24;
  *rr++ = w22;
  /* #112: @32 = @5[:3] */
  for (rr=w32, cs=w05+0; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #113: (@0[:12:4] = @32) */
  for (rr=w00+0, cs=w32; rr!=w00+12; rr+=4) *rr = *cs++;
  /* #114: {@4, @24, @22} = vertsplit(@30) */
  w04 = w30[0];
  w24 = w30[1];
  w22 = w30[2];
  /* #115: @30 = vertcat(@4, @24, @6, @22, @6) */
  rr=w30;
  *rr++ = w04;
  *rr++ = w24;
  *rr++ = w22;
  /* #116: @32 = @30[:3] */
  for (rr=w32, cs=w30+0; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #117: (@0[1:13:4] = @32) */
  for (rr=w00+1, cs=w32; rr!=w00+13; rr+=4) *rr = *cs++;
  /* #118: {@4, @24, @22} = vertsplit(@31) */
  w04 = w31[0];
  w24 = w31[1];
  w22 = w31[2];
  /* #119: @31 = vertcat(@4, @24, @6, @22, @6) */
  rr=w31;
  *rr++ = w04;
  *rr++ = w24;
  *rr++ = w22;
  /* #120: @32 = @31[:3] */
  for (rr=w32, cs=w31+0; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #121: (@0[2:14:4] = @32) */
  for (rr=w00+2, cs=w32; rr!=w00+14; rr+=4) *rr = *cs++;
  /* #122: @33 = @0' */
  casadi_trans(w00,casadi_s3, w33, casadi_s2, iw);
  /* #123: output[0][0] = @33 */
  casadi_copy(w33, 12, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real robot_model_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 96;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_e_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 6*sizeof(casadi_int);
  if (sz_w) *sz_w = 96*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
