/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_model_cost_y_0_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s1[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s2[23] = 
  {8, 8, 0, 0, 0, 0, 3, 6,
  6, 9, 12, 3, 4, 6, 3, 4,
  6, 3, 4, 6, 3, 4, 6};
static const casadi_int casadi_s3[23] = 
  {8, 8, 0, 0, 0, 0, 4, 8,
  8, 12, 12, 3, 4, 6, 7, 3,
  4, 6, 7, 3, 4, 6, 7};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {3, 1, 1};
static const casadi_int casadi_s6[3] = {0, 1, 1};
static const casadi_int casadi_s7[3] = {9, 1, 1};
static const casadi_int casadi_s8[3] = {0, 0, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* External functions */
int jac_adj1_y_expr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* jac_adj1_y_expr:(i0[3],out_o0[1x10,0nz],adj_o0[1x10],out_adj_i0[3x1,0nz])->(jac_adj_i0_i0[3x3],jac_adj_i0_out_o0[3x10,0nz],jac_adj_i0_adj_o0[3x10]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_adj1_y_expr(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* robot_model_cost_y_0_hess:(i0[5],i1[3],i2[0],i3[9],i4[],i5[0])->(o0[8x8,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *w00=w+3, *w02=w+15, w03, w04, w05, *w06=w+27, *w08=w+30, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, w25, w26, *w27=w+58, *w29=w+67, *w30=w+72, *w31=w+75, *w32=w+78, *w33=w+81;
  const casadi_real **arg1=arg+6, *cs, *wr27;
  /* #0: @0 = zeros(8x8,12nz) */
  casadi_clear(w00, 12);
  /* #1: @1 = 00 */
  /* #2: @2 = zeros(3x3) */
  casadi_clear(w02, 9);
  /* #3: @3 = input[0][0] */
  w03 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = vertcat(@3, @4, @5) */
  rr=w06;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  /* #7: @7 = zeros(1x10,0nz) */
  /* #8: @8 = zeros(1x10) */
  casadi_clear(w08, 10);
  /* #9: @3 = 0 */
  w03 = 0.;
  /* #10: @4 = input[0][4] */
  w04 = arg[0] ? arg[0][4] : 0;
  /* #11: @4 = fmax(@4,@3) */
  w04  = casadi_fmax(w04,w03);
  /* #12: @5 = 9 */
  w05 = 9.;
  /* #13: @4 = fmin(@4,@5) */
  w04  = casadi_fmin(w04,w05);
  /* #14: @3 = (@3<=@4) */
  w03  = (w03<=w04);
  /* #15: @9 = 0.9 */
  w09 = 9.0000000000000002e-01;
  /* #16: @10 = (@4<@9) */
  w10  = (w04<w09);
  /* #17: @3 = (@3&&@10) */
  w03  = (w03&&w10);
  /* #18: @10 = (!@3) */
  w10 = (! w03 );
  /* #19: @9 = (@9<=@4) */
  w09  = (w09<=w04);
  /* #20: @11 = 1.8 */
  w11 = 1.8000000000000000e+00;
  /* #21: @12 = (@4<@11) */
  w12  = (w04<w11);
  /* #22: @9 = (@9&&@12) */
  w09  = (w09&&w12);
  /* #23: @12 = (!@9) */
  w12 = (! w09 );
  /* #24: @11 = (@11<=@4) */
  w11  = (w11<=w04);
  /* #25: @13 = 2.7 */
  w13 = 2.7000000000000002e+00;
  /* #26: @14 = (@4<@13) */
  w14  = (w04<w13);
  /* #27: @11 = (@11&&@14) */
  w11  = (w11&&w14);
  /* #28: @14 = (!@11) */
  w14 = (! w11 );
  /* #29: @13 = (@13<=@4) */
  w13  = (w13<=w04);
  /* #30: @15 = 3.6 */
  w15 = 3.6000000000000001e+00;
  /* #31: @16 = (@4<@15) */
  w16  = (w04<w15);
  /* #32: @13 = (@13&&@16) */
  w13  = (w13&&w16);
  /* #33: @16 = (!@13) */
  w16 = (! w13 );
  /* #34: @15 = (@15<=@4) */
  w15  = (w15<=w04);
  /* #35: @17 = 4.5 */
  w17 = 4.5000000000000000e+00;
  /* #36: @18 = (@4<@17) */
  w18  = (w04<w17);
  /* #37: @15 = (@15&&@18) */
  w15  = (w15&&w18);
  /* #38: @18 = (!@15) */
  w18 = (! w15 );
  /* #39: @17 = (@17<=@4) */
  w17  = (w17<=w04);
  /* #40: @19 = 5.4 */
  w19 = 5.4000000000000004e+00;
  /* #41: @20 = (@4<@19) */
  w20  = (w04<w19);
  /* #42: @17 = (@17&&@20) */
  w17  = (w17&&w20);
  /* #43: @20 = (!@17) */
  w20 = (! w17 );
  /* #44: @19 = (@19<=@4) */
  w19  = (w19<=w04);
  /* #45: @21 = 6.3 */
  w21 = 6.2999999999999998e+00;
  /* #46: @22 = (@4<@21) */
  w22  = (w04<w21);
  /* #47: @19 = (@19&&@22) */
  w19  = (w19&&w22);
  /* #48: @22 = (!@19) */
  w22 = (! w19 );
  /* #49: @21 = (@21<=@4) */
  w21  = (w21<=w04);
  /* #50: @23 = 7.2 */
  w23 = 7.2000000000000002e+00;
  /* #51: @24 = (@4<@23) */
  w24  = (w04<w23);
  /* #52: @21 = (@21&&@24) */
  w21  = (w21&&w24);
  /* #53: @24 = (!@21) */
  w24 = (! w21 );
  /* #54: @23 = (@23<=@4) */
  w23  = (w23<=w04);
  /* #55: @25 = 8.1 */
  w25 = 8.0999999999999996e+00;
  /* #56: @26 = (@4<@25) */
  w26  = (w04<w25);
  /* #57: @23 = (@23&&@26) */
  w23  = (w23&&w26);
  /* #58: @26 = (!@23) */
  w26 = (! w23 );
  /* #59: @25 = (@25<=@4) */
  w25  = (w25<=w04);
  /* #60: @4 = (@4<@5) */
  w04  = (w04<w05);
  /* #61: @25 = (@25&&@4) */
  w25  = (w25&&w04);
  /* #62: @4 = (!@25) */
  w04 = (! w25 );
  /* #63: @27 = input[3][0] */
  wr27 = arg[3] ? arg[3] : casadi_zeros;
  /* #64: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5} = vertsplit(@27) */
  w05 = wr27[8];
  /* #65: @4 = (@4?@5:0) */
  w04  = (w04?w05:0);
  /* #66: @26 = (@26?@4:0) */
  w26  = (w26?w04:0);
  /* #67: @24 = (@24?@26:0) */
  w24  = (w24?w26:0);
  /* #68: @22 = (@22?@24:0) */
  w22  = (w22?w24:0);
  /* #69: @20 = (@20?@22:0) */
  w20  = (w20?w22:0);
  /* #70: @18 = (@18?@20:0) */
  w18  = (w18?w20:0);
  /* #71: @16 = (@16?@18:0) */
  w16  = (w16?w18:0);
  /* #72: @14 = (@14?@16:0) */
  w14  = (w14?w16:0);
  /* #73: @12 = (@12?@14:0) */
  w12  = (w12?w14:0);
  /* #74: @10 = (@10?@12:0) */
  w10  = (w10?w12:0);
  /* #75: (@8[9] += @10) */
  for (rr=w08+9, cs=(&w10); rr!=w08+10; rr+=1) *rr += *cs++;
  /* #76: @3 = (@3?@12:0) */
  w03  = (w03?w12:0);
  /* #77: (@8[0] += @3) */
  for (rr=w08+0, cs=(&w03); rr!=w08+1; rr+=1) *rr += *cs++;
  /* #78: @9 = (@9?@14:0) */
  w09  = (w09?w14:0);
  /* #79: (@8[1] += @9) */
  for (rr=w08+1, cs=(&w09); rr!=w08+2; rr+=1) *rr += *cs++;
  /* #80: @11 = (@11?@16:0) */
  w11  = (w11?w16:0);
  /* #81: (@8[2] += @11) */
  for (rr=w08+2, cs=(&w11); rr!=w08+3; rr+=1) *rr += *cs++;
  /* #82: @13 = (@13?@18:0) */
  w13  = (w13?w18:0);
  /* #83: (@8[3] += @13) */
  for (rr=w08+3, cs=(&w13); rr!=w08+4; rr+=1) *rr += *cs++;
  /* #84: @15 = (@15?@20:0) */
  w15  = (w15?w20:0);
  /* #85: (@8[4] += @15) */
  for (rr=w08+4, cs=(&w15); rr!=w08+5; rr+=1) *rr += *cs++;
  /* #86: @17 = (@17?@22:0) */
  w17  = (w17?w22:0);
  /* #87: (@8[5] += @17) */
  for (rr=w08+5, cs=(&w17); rr!=w08+6; rr+=1) *rr += *cs++;
  /* #88: @19 = (@19?@24:0) */
  w19  = (w19?w24:0);
  /* #89: (@8[6] += @19) */
  for (rr=w08+6, cs=(&w19); rr!=w08+7; rr+=1) *rr += *cs++;
  /* #90: @21 = (@21?@26:0) */
  w21  = (w21?w26:0);
  /* #91: (@8[7] += @21) */
  for (rr=w08+7, cs=(&w21); rr!=w08+8; rr+=1) *rr += *cs++;
  /* #92: @23 = (@23?@4:0) */
  w23  = (w23?w04:0);
  /* #93: (@8[8] += @23) */
  for (rr=w08+8, cs=(&w23); rr!=w08+9; rr+=1) *rr += *cs++;
  /* #94: @25 = (@25?@5:0) */
  w25  = (w25?w05:0);
  /* #95: (@8[9] += @25) */
  for (rr=w08+9, cs=(&w25); rr!=w08+10; rr+=1) *rr += *cs++;
  /* #96: @28 = zeros(3x1,0nz) */
  /* #97: {@27, NULL, NULL} = jac_adj1_y_expr(@6, @7, @8, @28) */
  arg1[0]=w06;
  arg1[1]=0;
  arg1[2]=w08;
  arg1[3]=0;
  res1[0]=w27;
  res1[1]=0;
  res1[2]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #98: @29 = ones(8x1,5nz) */
  casadi_fill(w29, 5, 1.);
  /* #99: {NULL, NULL, NULL, @25, NULL, NULL, NULL, NULL} = vertsplit(@29) */
  w25 = w29[3];
  /* #100: @5 = vertcat(@25, @1, @1) */
  rr=(&w05);
  *rr++ = w25;
  /* #101: @25 = ones(8x1,1nz) */
  w25 = 1.;
  /* #102: {NULL, NULL, NULL, NULL, @23, NULL, NULL, NULL} = vertsplit(@25) */
  w23 = w25;
  /* #103: @25 = vertcat(@1, @23, @1) */
  rr=(&w25);
  *rr++ = w23;
  /* #104: @23 = ones(8x1,1nz) */
  w23 = 1.;
  /* #105: {NULL, NULL, NULL, NULL, NULL, NULL, @4, NULL} = vertsplit(@23) */
  w04 = w23;
  /* #106: @23 = vertcat(@1, @1, @4) */
  rr=(&w23);
  *rr++ = w04;
  /* #107: @6 = horzcat(@5, @25, @23) */
  rr=w06;
  *rr++ = w05;
  *rr++ = w25;
  *rr++ = w23;
  /* #108: @2 = mac(@27,@6,@2) */
  casadi_mtimes(w27, casadi_s0, w06, casadi_s1, w02, casadi_s0, w, 0);
  /* #109: {@6, @30, @31} = horzsplit(@2) */
  casadi_copy(w02, 3, w06);
  casadi_copy(w02+3, 3, w30);
  casadi_copy(w02+6, 3, w31);
  /* #110: {@5, @25, @23} = vertsplit(@6) */
  w05 = w06[0];
  w25 = w06[1];
  w23 = w06[2];
  /* #111: @6 = vertcat(@1, @1, @1, @5, @25, @1, @23, @1) */
  rr=w06;
  *rr++ = w05;
  *rr++ = w25;
  *rr++ = w23;
  /* #112: @32 = @6[:3] */
  for (rr=w32, cs=w06+0; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #113: (@0[:12:4] = @32) */
  for (rr=w00+0, cs=w32; rr!=w00+12; rr+=4) *rr = *cs++;
  /* #114: {@5, @25, @23} = vertsplit(@30) */
  w05 = w30[0];
  w25 = w30[1];
  w23 = w30[2];
  /* #115: @30 = vertcat(@1, @1, @1, @5, @25, @1, @23, @1) */
  rr=w30;
  *rr++ = w05;
  *rr++ = w25;
  *rr++ = w23;
  /* #116: @32 = @30[:3] */
  for (rr=w32, cs=w30+0; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #117: (@0[1:13:4] = @32) */
  for (rr=w00+1, cs=w32; rr!=w00+13; rr+=4) *rr = *cs++;
  /* #118: {@5, @25, @23} = vertsplit(@31) */
  w05 = w31[0];
  w25 = w31[1];
  w23 = w31[2];
  /* #119: @31 = vertcat(@1, @1, @1, @5, @25, @1, @23, @1) */
  rr=w31;
  *rr++ = w05;
  *rr++ = w25;
  *rr++ = w23;
  /* #120: @32 = @31[:3] */
  for (rr=w32, cs=w31+0; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #121: (@0[2:14:4] = @32) */
  for (rr=w00+2, cs=w32; rr!=w00+14; rr+=4) *rr = *cs++;
  /* #122: @33 = @0' */
  casadi_trans(w00,casadi_s3, w33, casadi_s2, iw);
  /* #123: output[0][0] = @33 */
  casadi_copy(w33, 12, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_model_cost_y_0_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_0_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int robot_model_cost_y_0_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real robot_model_cost_y_0_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_0_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_cost_y_0_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_0_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    case 5: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_cost_y_0_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 93;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_cost_y_0_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 9*sizeof(casadi_int);
  if (sz_w) *sz_w = 93*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
