/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) robot_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[9] = 
  {8, 1, 0, 5, 2, 3, 5, 6,
  7};

/* robot_model_expl_vde_adj:(i0[5],i1[5],i2[3],i3[0])->(o0[8x1,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w0, w1, w2, *w3=w+3, *w4=w+8, w5, w6, w7, w8, w9;
  const casadi_real *cs;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #2: @2 = input[2][2] */
  w2 = arg[2] ? arg[2][2] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 5, w3);
  /* #4: @4 = (@2*@3) */
  for (i=0, rr=w4, cs=w3; i<5; ++i) (*rr++)  = (w2*(*cs++));
  /* #5: {@2, @5, @6, @7, NULL} = vertsplit(@4) */
  w2 = w4[0];
  w5 = w4[1];
  w6 = w4[2];
  w7 = w4[3];
  /* #6: @8 = (@1*@5) */
  w8  = (w1*w5);
  /* #7: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #8: @9 = (@0*@2) */
  w9  = (w0*w2);
  /* #9: @8 = (@8+@9) */
  w8 += w9;
  /* #10: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #11: @8 = input[0][2] */
  w8 = arg[0] ? arg[0][2] : 0;
  /* #12: @5 = (@8*@5) */
  w5  = (w8*w5);
  /* #13: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #14: @2 = (@8*@2) */
  w2  = (w8*w2);
  /* #15: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #16: @5 = (@5-@2) */
  w5 -= w2;
  /* #17: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #18: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #19: output[0][3] = @7 */
  if (res[0]) res[0][3] = w7;
  /* #20: @0 = (@8*@0) */
  w0  = (w8*w0);
  /* #21: @8 = (@8*@1) */
  w8 *= w1;
  /* #22: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #23: @7 = input[2][1] */
  w7 = arg[2] ? arg[2][1] : 0;
  /* #24: @6 = 1 */
  w6 = 1.;
  /* #25: @4 = vertcat(@0, @8, @1, @7, @6) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w8;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w6;
  /* #26: @0 = dot(@4, @3) */
  w0 = casadi_dot(5, w4, w3);
  /* #27: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void robot_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int robot_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int robot_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real robot_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* robot_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* robot_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 18;
  return 0;
}

CASADI_SYMBOL_EXPORT int robot_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 18*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
